### ISSUE TITLE
UI broken on Firefox & Chrome TTRSS v.1.12

### ISSUE THREAD

**Issue by jaranta** [levito/tt-rss-feedly-theme#7] opened 2014-03-25 07:55 UTC
There are several problems with the UI on the v.1.12 of TTRSS on both Firefox and Chrome.

~~1. The arrows for categories are not visible, but are clickable.~~ My bad, fixed bad permission and this was corrected.
2. If the buttons on the top row do not fit the screen, some of them are left outside the browser-window. See attached picture -- it is lacking the options-button.
3. If a button not completely visible on the screen is pressed, it refocuses the window without providing a scroll-bar.

![ttrss](https://f.cloud.github.com/assets/5079912/2509406/d3440026-b3f1-11e3-9193-93ce8548993a.png)

**Comment by levito** [comment] 2018-04-03 08:30
I can't reproduce this anymore so I consider this fixed, closing.

**Closed by levito** 2018-04-03 08:30 UTC
